[tool.poetry]
name = "pypatches"
version = "0.0.1"
description = ""
authors = ["Alberto Cetoli <alberto.cetoli@fractalego.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
